site_name: Plural Respect
site_url: https://pluralrespect.neocities.org
site_description: A crash course for/in plurality.
#copyright: CC-BY-SA 4.0 International

nav:
  - About This Site: index.md
  - Shattering Expectations: expectations.md
  - Building Understanding: understanding.md
  - External Challenges: challenges.md

theme: windmill

extra_css:
    - css/theme-adjustments.css

extra:
  version: 2.0.0
  logo: img/custom-journey-flag.png
  article_nav_top: false